# Generated by Django 4.0.4 on 2022-04-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque', models.FileField(upload_to='cheques', verbose_name='PDF чека')),
                ('qrcode', models.ImageField(upload_to='qrcodes', verbose_name='Изображение QRCode')),
            ],
        ),
    ]
