# Generated by Django 4.0.4 on 2022-04-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cheque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='qrcode',
        ),
    ]
